Controllers/ChuDesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebBanSachOnline.Models;

namespace WebBanSachOnline.Controllers
{
    public class ChuDesController : Controller
    {
        private MVCBanSachOnlineEntities db = new MVCBanSachOnlineEntities();

        // GET: ChuDes
        public ActionResult Index()
        {
            return View(db.ChuDe.ToList());
        }

        // GET: ChuDes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChuDe chuDe = db.ChuDe.Find(id);
            if (chuDe == null)
            {
                return HttpNotFound();
            }
            return View(chuDe);
        }

        // GET: ChuDes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ChuDes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaChuDe,TenChuDe")] ChuDe chuDe)
        {
            if (ModelState.IsValid)
            {
                db.ChuDe.Add(chuDe);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(chuDe);
        }

        // GET: ChuDes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChuDe chuDe = db.ChuDe.Find(id);
            if (chuDe == null)
            {
                return HttpNotFound();
            }
            return View(chuDe);
        }

        // POST: ChuDes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaChuDe,TenChuDe")] ChuDe chuDe)
        {
            if (ModelState.IsValid)
            {
                db.Entry(chuDe).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(chuDe);
        }

        // GET: ChuDes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChuDe chuDe = db.ChuDe.Find(id);
            if (chuDe == null)
            {
                return HttpNotFound();
            }
            return View(chuDe);
        }

        // POST: ChuDes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ChuDe chuDe = db.ChuDe.Find(id);
            db.ChuDe.Remove(chuDe);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/SachesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebBanSachOnline.Models;

namespace WebBanSachOnline.Controllers
{
    public class SachesController : Controller
    {
        private MVCBanSachOnlineEntities db = new MVCBanSachOnlineEntities();

        // GET: Saches
        public ActionResult Index()
        {
            var saches = db.Sach.Include(s => s.ChuDe).Include(s => s.NhaXuatBan);
            return View(saches.ToList());
        }

        // GET: Saches/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sach sach = db.Sach.Find(id);
            if (sach == null)
            {
                return HttpNotFound();
            }
            return View(sach);
        }

        // GET: Saches/Create
        public ActionResult Create()
        {
            ViewBag.MaChuDe = new SelectList(db.ChuDe, "MaChuDe", "TenChuDe");
            ViewBag.MaNXB = new SelectList(db.NhaXuatBan, "MaNXB", "TenNXB");
            return View();
        }

        // POST: Saches/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaSach,TenSach,GiaBan,MoTa,AnhBia,NgayCapNhat,SoLuongTon,MaNXB,MaChuDe")] Sach sach, HttpPostedFileBase AnhBia)
        {
            if (ModelState.IsValid)
            {
                if(AnhBia !=null)
                {
                    //Lấy tên file của hình được up lên
                    var fileName = Path.GetFileName(AnhBia.FileName);
                   //Tạo đường dẫn tới file
                    var path = Path.Combine(Server.MapPath("~/Content/assets/image/"), fileName);
                    //Lưu tên
                    sach.AnhBia = fileName;
                    //Lưu vào Ảnh bìa
                    AnhBia.SaveAs(path);
                }
                db.Sach.Add(sach);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaChuDe = new SelectList(db.ChuDe, "MaChuDe", "TenChuDe", sach.MaChuDe);
            ViewBag.MaNXB = new SelectList(db.NhaXuatBan, "MaNXB", "TenNXB", sach.MaNXB);
            return View(sach);
        }

        // GET: Saches/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sach sach = db.Sach.Find(id);
            if (sach == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaChuDe = new SelectList(db.ChuDe, "MaChuDe", "TenChuDe", sach.MaChuDe);
            ViewBag.MaNXB = new SelectList(db.NhaXuatBan, "MaNXB", "TenNXB", sach.MaNXB);
            return View(sach);
        }

        // POST: Saches/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSach,TenSach,GiaBan,MoTa,AnhBia,NgayCapNhat,SoLuongTon,MaNXB,MaChuDe")] Sach sach, HttpPostedFileBase AnhBia)
        {
            if (ModelState.IsValid)
            {
                var productDB = db.Sach.FirstOrDefault(p => p.MaSach == sach.MaSach);
                if (productDB == null)
                {
                    return HttpNotFound();
                }

                // Assign values to productDB properties
                productDB.TenSach = sach.TenSach;
                productDB.GiaBan = sach.GiaBan;
                productDB.MoTa = sach.MoTa;
                if (AnhBia != null)
                {
                    var fileName = Path.GetFileName(AnhBia.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/assets/HinhAnhSach"), fileName);
                    productDB.AnhBia = fileName;
                    AnhBia.SaveAs(path);
                }
                productDB.NgayCapNhat = sach.NgayCapNhat;
                productDB.SoLuongTon = sach.SoLuongTon;
                productDB.MaNXB = sach.MaNXB;
                productDB.MaChuDe = sach.MaChuDe;

                db.Entry(productDB).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaChuDe = new SelectList(db.ChuDe, "MaChuDe", "TenChuDe", sach.MaChuDe);
            ViewBag.MaNXB = new SelectList(db.NhaXuatBan, "MaNXB", "TenNXB", sach.MaNXB);
            return View(sach);
        }

        // GET: Saches/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sach sach = db.Sach.Find(id);
            if (sach == null)
            {
                return HttpNotFound();
            }
            return View(sach);
        }

        // POST: Saches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sach sach = db.Sach.Find(id);
            db.Sach.Remove(sach);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_AdminFooter.cshtml
<div class="container-fluid px-4">
    <div class="d-flex align-items-center justify-content-between small">
        <div class="text-muted">Copyright &copy; BookStore 2023</div>
        <div>
            <a href="#">Privacy Policy</a>
            &middot;
            <a href="#">Terms &amp; Conditions</a>
        </div>
    </div>
</div>

Views/Shared/_AdminHeader.cshtml
    <a class="navbar-brand ps-3" href="index.html">Admin</a>

<button class="btn btn-link btn-sm order-1 order-1g-0 me-4 me-lg-0" id="sidebarToggle" href="#!" ><i class="fas fa-bars"></i></button>

<form class="d-none d-md-inline-block form-inline ms-auto me-md-3 my-2 my-md-0">
    <div class="input-group">
        <input class="form-control" type="text" placeholder="search for..." aria-label="search for..." aria-describedby="btnNavbarSearch"  />
        <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
    </div>
</form>

Views/Shared/_AdminSideBar.cshtml
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordin">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <a class="nav-link" href="@Url.Action("IndexDonhang","Admin")">Đơn Hàng</a>
                <a class="nav-link" href="@Url.Action("IndexSach","Admin")">Sách</a>
                <a class="nav-link" href="@Url.Action("IndexChuDe","Admin")">Chủ Đề</a>
                <a class="nav-link" href="@Url.Action("IndexNXB","Admin")">Nhà Xuất Bản</a>
                <a class="nav-link" href="@Url.Action("DangXuat","User")">Đăng Xuất </a>
            </div>
        </div>
        <div class="sb-sidenav-footer">
            <div class="small">Logged in as:</div>
            Admin
        </div>
    </nav>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @*@Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")*@
    <link href="~/Content/css/layouts/grid.module.css" rel="stylesheet" />
    <link href="~/Content/css/helpers/extend.module.css" rel="stylesheet" />
    <link href="~/Content/css/helpers/variable.module.css" rel="stylesheet" />
    <link href="~/Content/css/main.css" rel="stylesheet" />
    <link href="~/Content/css/components/slider/slider.module.css" rel="stylesheet" />
    <link href="~/Content/css/components/productDesc/productDesc.module.css" rel="stylesheet" />
    <link href="~/Content/css/components/pagination/pagination.module.css" rel="stylesheet" />
    <link href="~/Content/css/components/optionPromo/optionPromo.module.css" rel="stylesheet" />
    <link href="~/Content/css/components/hotDeal/hotDeal.module.css" rel="stylesheet" />
    <link href="~/Content/css/components/header/headerTop.module.css" rel="stylesheet" />
    <link href="~/Content/css/components/header/headerMain.module.css" rel="stylesheet" />
    <link href="~/Content/css/components/footer/footer.module.css" rel="stylesheet" />
    <link href="~/Content/css/components/discountPayonl/discountPayonl.module.css" rel="stylesheet" />
    <link href="~/Content/css/components/dailySg/dailySg.module.css" rel="stylesheet" />
    <link href="~/Content/css/components/banner/banner.module.css" rel="stylesheet" />
    <link href="~/Content/css/base/reset.module.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            @*<div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>*@
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    @*<script src="~/Content/Admin/js/jquery-1.9.1.min.js"></script>
    <script src="~/Content/Admin/js/jquery-migrate-1.0.0.min.js"></script>
    <script src="~/Content/Admin/js/jquery-ui-1.10.0.custom.min.js"></script>
    <link href="~/Content/Admin/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Admin/bootstrap.min.css" rel="stylesheet" />*@
</body>
</html>

Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Admin</title>
    <link href="" />
    <link href="~/Content/Admin/style.css" rel="stylesheet" />
    <link href="~/Content/Admin/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Admin/bootstrap-responsive.min.css" rel="stylesheet" />
    <link href="~/Content/Admin/bootstrap-responsive.css" rel="stylesheet" />
    <link href="~/Content/Admin/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Admin/font-awesome-ie7.min.css" rel="stylesheet" />
    <link href="~/Content/Admin/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/Admin/style-forms.css" rel="stylesheet" />
    <link href="~/Content/Admin/uploadify.css" rel="stylesheet" />
    <link href="~/Content/Admin/style-responsive.css" rel="stylesheet" />
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar-expand navbar-dark bg-dark">
        @Html.Partial("~/Views/Shared/_AdminHeader.cshtml")
    </nav>
    <div id="layoutsidenav">
        @Html.Partial("~/Views/Shared/_AdminSideBar.cshtml")
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    <div class="card-body">
                        @RenderBody()
                    </div>
                </div>
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                @Html.Partial("~/Views/Shared/_AdminFooter.cshtml")
            </footer>
        </div>
    </div>
</body>
<script src="~/Scripts/bootstrap.bundle.min.js"></script>
</html>

Views/Shared/_LayoutLog.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/assets/icon/fontawesome-free-6.1.1-web/fontawesome-free-6.1.1-web/css/fontawesome.min.css" rel="stylesheet" />
    <link href="~/Content/Admin/font-awesome.min.css" rel="stylesheet" />

    <link href="~/Content/css/layouts/login.css" rel="stylesheet" />
</head>
<body>
   
    <div id="div-main">
        @RenderBody()
    </div>
        
    
   
</body>
</html>

Views/Shared/_MasterLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/assets/icon/fontawesome-free-6.1.1-web/fontawesome-free-6.1.1-web/css/fontawesome.min.css" rel="stylesheet" />
    <link href="~/Content/Admin/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/css/layouts/mystyle.css" />
</head>
<body>
    <div id="header" style="display: flex; background-color: aqua; height: 3.3rem !important;justify-content:center;width: auto;">
        <div id="div-top_v1">
            <a class="navbar-brand ps-3" href="#">Admin</a>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
            <button class="btn btn-link btn-sm order-1 order-1g-0 me-4 me-lg-0" id="sidebarToggle" href="#">
                <i class="fas fa-bars"></i>
            </button>

            <form class="d-none d-md-inline-block form-inline ms-auto me-md-3 my-2 my-md-0" style="margin-top:6px !important; width:25rem;">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="search for..." aria-label="search for..." aria-describedby="btnNavbarSearch" />
                    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
                    <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
                </div>
            </form>
        </div>
        <div id="div-top_v2">
            <!-- Grey with black text -->
            <!--<nav class="navbar navbar-expand-lg navbar-light">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Action("Index","Saches")">
                            PRODUCT STORE
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="~/Products">
                            ADMIN PRODUCT
                        </a>
                    </li>-->
                    @*<li class="nav-item">
                        <a class="nav-link"
                           href="~/CustomerProducts">CUSTOMER PRODUCT</a>
                    </li>*@
                    <!--<li class="nav-item">
                        <a class="nav-link" href="#">CONTACT</a>
                    </li>
                </ul>

            </nav>-->
        </div>
    </div>
   
    <br />
    <div id="div-main">
        <div id="div-left">
            <ul style="list-style: none; padding-left: 0px;">
                <li>
                    <a class="nav-link" href="@Url.Action("IndexDonhang","Admin")">Đơn Hàng</a>
                </li>
                <li>
                    <a class="nav-link" href="@Url.Action("Index","Saches")">Sách</a>

                </li>
                <li>
                    <a class="nav-link" href="@Url.Action("Index","ChuDes")">Chủ Đề</a>
                </li>
                <li>
                    <a class="nav-link" href="@Url.Action("Index","NhaXuatBans")">Nhà Xuất Bản</a>
                </li>
                <li>
                    <a class="nav-link" href="@Url.Action("DangXuat","User")">Đăng Xuất </a>
                </li>
            </ul>

            @*<div class="sb-sidenav-footer">
                <div class="small">Logged in as:</div>
                Admin
            </div>*@
            @*<h3>Danh mục quản lý</h3>
                <ul style="list-style: none">
                    <li>
                        <a href="ChuDes">Chủ đề</a>
                    </li>
                    <li>
                        <a href="NhaXuatBans">Nhà xuất bản</a>
                    </li>
                    <li>
                        <a href="TacGias">Tác giả</a>
                    </li>
                    <li>
                        <a href="Sách">Sách</a>
                    </li>
                </ul>*@
        </div>
        <div id="div-right" style="height:150vh;">
            @RenderBody()
        </div>
    </div>
       <div id="div-footer" style="height: 5rem; bottom: auto;">
        <div class="container-fluid px-4">
            <div class="d-flex align-items-center justify-content-between medium">
                <div class="text-muted" style=" color: rgba(0,0,0,.7); text-shadow: 0 1px rgba(255, 255, 255, 0.1);">© Copyright 2023 BookStore . All rights reserved. </div>
                <div>
                    <a href="#">Privacy Policy</a>
                    &middot;
                    <a href="#">Terms &amp; Conditions</a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>